# homebrew-tap/.github/workflows/update-formula.yml

name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Formula
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          chmod +x .github/scripts/update-formula.sh
          .github/scripts/update-formula.sh $VERSION

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/localcloud.rb
          git commit -m "Update LocalCloud to ${{ github.event.client_payload.version }}"
          git push