# homebrew-tap/.github/workflows/update-formula.yml

name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Formula
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          echo "Updating LocalCloud formula to $VERSION"
          chmod +x .github/scripts/update-formula.sh
          ./.github/scripts/update-formula.sh "$VERSION"

      - name: Commit and Push
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          if git diff --quiet Formula/localcloud.rb; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add Formula/localcloud.rb
          git commit -m "Update LocalCloud to $VERSION

- Update version and SHA256 hashes automatically
- Downloaded and verified all platform releases

🤖 Automated by GitHub Actions"
          git push