# homebrew-tap/.github/workflows/update-formula.yml

name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug - Show directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Checking for Formula directory:"
          ls -la Formula/ || echo "Formula directory not found"

      - name: Update Formula
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          echo "Updating formula to version $VERSION"
          chmod +x .github/scripts/update-formula-simple.sh
          ./.github/scripts/update-formula-simple.sh $VERSION

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/localcloud.rb
          git commit -m "Update LocalCloud to ${{ github.event.client_payload.version }}"
          git push